/*
	Civilization
	Authors: ChimpanG
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT INTO	Types
		(Type,								Kind				)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'KIND_CIVILIZATION'	);
		
-----------------------------------------------
-- Civilizations
-----------------------------------------------

INSERT INTO	Civilizations
		(CivilizationType,					Name,										Description,										Adjective,										StartingCivilizationLevelType,		RandomCityNameDepth,	Ethnicity			)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CIVILIZATION_CVS_PHILIPPINES_NAME',	'LOC_CIVILIZATION_CVS_PHILIPPINES_DESCRIPTION',		'LOC_CIVILIZATION_CVS_PHILIPPINES_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',		90,						'ETHNICITY_ASIAN' 	);
		
-----------------------------------------------
-- CityNames
-----------------------------------------------

INSERT INTO	CityNames
		(CivilizationType,					CityName							)						
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MANILA'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_QUEZON'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_DAVAO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CALOOCAN'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CDO'	    		   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CEBU'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_PASIG'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_ZAMBOANGA'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TAGUIG'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_ANTIPOLO'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CAGAYAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_PARANQUE'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_DASMARINAS'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_VALENZUELA'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_BACOOR'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MACTAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_LAS_PINAS'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_PUERTO_PRINCESA'		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_COTABATO'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_NAGA'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_ILOILO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_BUTUAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_PALAYAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_ROXAS'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MAKATI'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SAN_JOSE_DEL_MONTE'	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_BACOLOD'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MUNTINLUPA'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CALAMBA'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MARIKINA'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_PASAY'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_ANGELES'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_IMUS'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MANDALUYONG'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MALABON'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MANDAUE'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SANTA_ROSA'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_BAGUIO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_ILIGAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TARLAC'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_BINAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_LIPA'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_BATANGAS'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CAVITE'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SAN_PEDRO'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CABUYAO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SAN_FERNANDO'		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CABANATUAN'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_LUCENA'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SAN_PABLO'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TAGUM'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MALOLOS'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MABALACAT'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TACURONG'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_NAVOTAS'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TACLOBAN'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_OLONGAPO'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TALISAY'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_ORMOC'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MEYCAUAYAN'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MARAWI'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_PAGADIAN'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_LEGAZPI'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_PANABO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CALBAYOG'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_KABANKALAN'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_KORONADAL'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MALAYBALAY'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TANAUAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_DAGUPAN'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_BAGO'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_DIGOS'				),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SORSOGON'			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SFLU'		    	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_DUMAGUETE'	    	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TAGBILARAN'	    	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_VIGAN'	    		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TAGAYTAY'	  	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TABUK'	 	 	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_ISABELA'	 	 	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_VICTORIAS'	 	 	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TAYABAS'	 	 	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_SURIGAO'	 	 	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TUGUEGARAO'	 	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_OROQUIETA'	 	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_URDANETA'	 	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_DAPITAN'	    	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_OZAMIZ'	    	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CALAPAN'	    	   	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_CATBALOGAN'	     	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_BATAC'	   		  	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_DIPOLOG'	   		  	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_MAASIN'	   		  	),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITY_NAME_TACURONG'	       	);
		
-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------

INSERT INTO	CivilizationCitizenNames
		(CivilizationType,					CitizenName,								Female	)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_MALE_1',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_MALE_2',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_MALE_3',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_MALE_4',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_MALE_5',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_MALE_6',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_MALE_7',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_MALE_8',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_MALE_9',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_MALE_10',		0 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_1',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_2',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_3',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_4',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_5',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_6',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_7',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_8',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_9',		1 		),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CITIZEN_CVS_PHILIPPINES_FEMALE_10',	1 		);

-----------------------------------------------
-- CivilizationInfo
-----------------------------------------------

INSERT INTO	CivilizationInfo
		(CivilizationType,					Header,						Caption,									SortIndex	)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_CVS_PHILIPPINES_LOCATION',		10			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_CVS_PHILIPPINES_SIZE',			20			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_CVS_PHILIPPINES_POPULATION',	30			),
		('CIVILIZATION_CVS_PHILIPPINES',	'LOC_CIVINFO_CAPITAL',		'LOC_CIVINFO_CVS_PHILIPPINES_CAPITAL',		40			);
		
-----------------------------------------------
-- Start Bias
-----------------------------------------------

INSERT INTO	StartBiasFeatures
		(CivilizationType,					FeatureType,		Tier	)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'FEATURE_JUNGLE',	3		);

INSERT INTO	StartBiasTerrains
		(CivilizationType,					TerrainType,	 	Tier	)
VALUES	('CIVILIZATION_CVS_PHILIPPINES',	'TERRAIN_COAST',	2		);

-----------------------------------------------
-- RequirementSets
-----------------------------------------------

INSERT INTO RequirementSets
        (RequirementSetId,						RequirementSetType			)
VALUES	('REQSET_CVS_PLAYER_IS_PHILIPPINES',	'REQUIREMENTSET_TEST_ALL'	),
		('REQSET_CVS_LEADER_IS_PHILIPPINES',	'REQUIREMENTSET_TEST_ANY'	);

-----------------------------------------------
-- RequirementSetRequirements
-----------------------------------------------

INSERT INTO RequirementSetRequirements
        (RequirementSetId,						RequirementId					)
VALUES	('REQSET_CVS_PLAYER_IS_PHILIPPINES',	'REQ_CVS_PLAYER_IS_PHILIPPINES'	);

-----------------------------------------------
-- Requirements
-----------------------------------------------

INSERT INTO Requirements
		(RequirementId,						RequirementType						)
VALUES	('REQ_CVS_PLAYER_IS_PHILIPPINES',	'REQUIREMENT_REQUIREMENTSET_IS_MET'	);

-----------------------------------------------
-- RequirementArguments
-----------------------------------------------

INSERT INTO RequirementArguments
		(RequirementId,						Name,				Value								)
VALUES	('REQ_CVS_PLAYER_IS_PHILIPPINES',	'RequirementSetId', 'REQSET_CVS_LEADER_IS_PHILIPPINES'	);